version: "3.8"

services:
  movies_admin:
    container_name: movies-admin-app
    build:
      context: ../movies_admin/
      dockerfile: ../docker_compose/Dockerfile
      args:
        BUILD_MODE: dev
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.db
    restart: unless-stopped
    volumes:
      - ../movies_admin:/home/app/web:delegated # enable hot code reload in debug mode
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    container_name: movies-admin-postgres
    image: postgres:13.0-alpine
    env_file:
      - ./.envs/.dev/.db
    restart: unless-stopped
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      # Create db schema on container first launch
      - ./utils/create_postgres_schema:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  nginx:
    container_name: movies-admin-nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - movies_admin

  elasticsearch:
    container_name: movies-admin-elasticsearch
    image: elasticsearch:8.10.2
    restart: always
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: curl -s http://movies-admin-elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 9200:9200
      - 9300:9300

  etl:
    container_name: movies-admin-etl
    build:
      context: ../postgres_to_es/
      dockerfile: ./Dockerfile.etl
    env_file:
      - ../postgres_to_es/.env
    restart: unless-stopped
    depends_on:
      - postgres
      - elasticsearch


volumes:
  postgres_volume:
  static_volume:
  elasticsearch_volume:
